import test from 'node:test';
import assert from 'node:assert/strict';
import { Arena,newSession } from '../web/src/v2/game.js';
import { freshProfile, ProfileStore, validateProfile, encode, decode, KEY, LEGACY } from '../web/src/v2/store.js';
import { newState } from '../web/src/game.js';
import { encodeSave } from '../web/src/store.js';
import { firstWall, segmentCircle, moveCircle, visible } from '../web/src/v2/geometry.js';
import { ROOM,WEAPONS } from '../web/src/v2/data.js';
const tick=(g,seconds)=>{for(let i=0;i<Math.round(seconds*60);i++)g.update(1/60);};
test('practice targets can be saved from their first moving frame',()=>{const v=freshProfile(),g=new Arena(v.session);for(let i=0;i<180;i++){g.update(1/60);assert.equal(validateProfile(v),true,`practice frame ${i}`);}});
function memory(){const m=new Map();return {getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k)};}
function bullet(values={}){return {id:10,group:7,team:'enemy',kind:'round',x:100,y:100,vx:0,vy:0,damage:1,r:2,remaining:400,pierce:0,hit:[],source:'archer',...values};}
test('v2 movement stays two-dimensional and firing never clears movement',()=>{const g=new Arena();g.p.x=100;g.p.y=240;g.input={x:1,y:1};g.pressAttack();tick(g,.5);assert.ok(g.p.x>130&&g.p.y>270);assert.equal(g.input.x,1);assert.ok(g.s.shots>=2);});
test('v2 single tap fires once; hold follows weapon interval, swap preserves movement/cooldowns',()=>{const g=new Arena();g.pressAttack();g.releaseAttack();tick(g,.5);assert.equal(g.s.shots,1);g.pressAttack();tick(g,.1);const remaining=g.p.cooldowns[1];g.input={x:1,y:0};g.swap();assert.equal(g.attackHeld,false);assert.equal(g.input.x,1);assert.equal(g.p.cooldowns[1],remaining);assert.equal(g.fire(),false);tick(g,.2);g.swap();assert.ok(g.p.switchTime>0);});
test('v2 walls win before enemies and swept bullets do not tunnel',()=>{const a={x:0,y:50},b={x:200,y:50};assert.equal(firstWall(a,b,[{x:50,y:40,w:2,h:20}],2),.24);assert.ok(segmentCircle(a,b,{x:100,y:50},5)>.24);const g=new Arena(newSession());g.s.enemies=[{...g.s.enemies[0],id:1,x:230,y:130,hp:40}];g.s.bullets=[bullet({team:'friend',source:'P01',x:180,y:130,vx:5000,damage:8})];g.updateBullets(1/60);assert.equal(g.s.enemies[0].hp,40);assert.equal(g.s.bullets.length,0);g.s.enemies[0].x=170;g.s.bullets=[bullet({team:'friend',source:'P01',x:140,y:130,vx:5000,damage:8})];g.updateBullets(1/60);assert.equal(g.s.enemies[0].hp,32);});
test('v2 assist excludes blocked/out-of-range targets; manual aiming overrides',()=>{const g=new Arena();g.p.x=160;g.p.y=130;g.s.enemies=[{...g.s.enemies[0],id:1,x:250,y:130},{...g.s.enemies[1],id:2,x:160,y:200}];g.updateAim(.1);assert.equal(g.s.targetId,2);g.aim(-1,true);g.updateAim(.2);assert.equal(g.p.angle,-1);assert.equal(g.s.targetId,null);g.manualHeld=false;g.manualTime=.25;g.updateAim(.1);assert.equal(g.s.targetId,null);g.updateAim(.2);g.updateAim(.02);assert.equal(g.s.targetId,2);});
test('v2 same enemy shotgun package settles maximum damage once, shield overflow and invulnerability',()=>{const g=new Arena(newSession('trial'));g.p.x=100;g.p.y=100;g.p.shield=1;g.s.bullets=[bullet({damage:1}),bullet({id:11,damage:2})];g.updateBullets(.01);assert.equal(g.p.shield,0);assert.equal(g.p.hp,5);assert.equal(g.s.damageTaken,2);assert.equal(g.p.breakBoost,1);assert.equal(g.hurt(2),false);});
test('v2 shield regeneration starts after four seconds; lamp halves damage and clears ordinary bullets',()=>{const g=new Arena(newSession('trial'));g.s.preview=100;g.p.shield=2;g.p.lastHurt=0;tick(g,4.9);assert.equal(g.p.shield,2);tick(g,.15);assert.equal(g.p.shield,3);g.skill();g.p.invulnerable=0;g.hurt(2);assert.equal(g.p.shield,2);g.s.bullets=[bullet({x:g.p.x+15,y:g.p.y})];g.updateBullets(.01);assert.equal(g.s.bullets.length,0);assert.equal(g.skill(),false);});
test('v2 dash travels thirty, cannot cross walls, and recharges serially',()=>{const g=new Arena();g.p.x=100;g.p.y=250;g.input={x:1,y:0};g.dash();g.input={x:0,y:0};tick(g,.18);assert.ok(Math.abs(g.p.x-130)<.2);g.p.x=180;g.p.y=140;g.input={x:1,y:0};g.dash();g.input={x:0,y:0};tick(g,.18);assert.ok(g.p.x<=183);assert.equal(g.p.dashCharges,0);tick(g,2.45);assert.equal(g.p.dashCharges,1);tick(g,2.8);assert.equal(g.p.dashCharges,2);});
test('v2 sword clears only the forward sector in effective frames, one hit per swing',()=>{const g=new Arena();g.p.x=100;g.p.y=100;g.p.active=0;g.aim(0,true);g.s.enemies=[];g.s.bullets=[bullet({x:115,y:100}),bullet({id:11,x:85,y:100})];g.pressAttack();g.releaseAttack();tick(g,.02);assert.equal(g.s.bullets.length,2);tick(g,.04);assert.equal(g.s.bullets.length,1);assert.equal(g.s.bullets[0].id,11);});
test('v2 zero energy can obtain free fallback without refilling energy',()=>{const g=new Arena(newSession('trial',['S01','W01']));g.p.energy=0;assert.equal(g.fire(),false);assert.equal(g.emergencyWeapon(),true);assert.equal(g.weapon.id,'P01');assert.equal(g.p.energy,0);g.s.preview=100;tick(g,.2);assert.equal(g.fire(),true);});
test('v2 spawn is telegraphed at least eighty away; clear rewards persist atomically without reload farming',()=>{const g=new Arena(newSession('trial'));g.spawnWave();assert.ok(g.s.enemies.every(e=>e.state==='spawn'&&Math.hypot(e.x-g.p.x,e.y-g.p.y)>=80));for(const e of g.s.enemies)e.hp=0;g.update(1/60);assert.deepEqual(g.s.rewarded,[0]);assert.equal(g.s.copper,10);const v=freshProfile();v.session=g.s;assert.equal(validateProfile(v),true);const resumed=new Arena(decode(encode(v)).session);tick(resumed,.2);assert.equal(resumed.s.copper,10);assert.deepEqual(resumed.s.rewarded,[0]);});
test('v2 pause freezes world, clears held shooting, and resumes without catch-up',()=>{const g=new Arena();g.pressAttack();g.pause();const json=JSON.stringify(g.s);tick(g,3);assert.equal(JSON.stringify(g.s),json);g.resume();tick(g,1);assert.equal(g.s.shots,1);});
test('v2 full snapshots validate through trial actions and bullets',()=>{const v=freshProfile();v.session=newSession('trial');const g=new Arena(v.session);g.pressAttack();for(let i=0;i<600&&!g.s.dead;i++){g.input={x:Math.cos(i/120),y:Math.sin(i/120)};if(i%100===0)g.skill();if(i%90===0)g.dash();g.update(1/60);assert.equal(validateProfile(v),true,`frame ${i}`);}assert.deepEqual(decode(encode(v)),v);});
test('v2 migration backs up exact legacy bytes, safely exits old room and preserves upgrades/potions',()=>{for(const ending of ['honesty','silence']){const storage=memory(),old=newState();old.stage=10;old.ending=ending;old.flags.core=true;old.flags.tag=true;old.scene='dungeon';old.player.weapon=1;old.player.potions=3;old.inventory.coins=93;old.inventory.iron=7;const raw=encodeSave(old);storage.setItem(LEGACY,raw);const store=new ProfileStore(storage),v=store.load();assert.equal(store.blocked,false,store.error);assert.equal(v.legacy.ending,ending);assert.equal(v.legacy.coins,93);assert.equal(v.legacy.iron,13);assert.equal(v.legacy.warehousePotions,1);assert.equal(v.legacy.memorial,true);assert.equal(v.session.mode,'practice');assert.equal(storage.getItem(LEGACY),raw);assert.equal(storage.getItem(LEGACY+'.before-v2'),raw);assert.equal(store.load().legacy.iron,13);}});
test('v2 damaged source and failed backups never overwrite legacy data',()=>{const storage=memory();storage.setItem(LEGACY,'broken');const store=new ProfileStore(storage);store.load();assert.equal(store.blocked,true);assert.equal(storage.getItem(LEGACY),'broken');assert.equal(store.write(freshProfile()),false);const old=encodeSave(newState());const broken={getItem:k=>k===LEGACY?old:null,setItem(){throw Error('quota');}};const fail=new ProfileStore(broken);fail.load();assert.equal(fail.blocked,true);});
test('v2 invalid imports are rejected, valid prior backup recovers without overwriting corruption',()=>{const storage=memory(),store=new ProfileStore(storage),v=freshProfile();store.write(v);v.trialWins=1;store.write(v);storage.setItem(KEY,'damaged');const recover=new ProfileStore(storage);assert.equal(recover.load().trialWins,0);assert.equal(recover.recovered,true);assert.equal(storage.getItem(KEY),'damaged');assert.throws(()=>recover.import('{}'));const bad=freshProfile();bad.session.player.energy=NaN;assert.equal(validateProfile(bad),false);});
