import { Arena, newSession } from './game.js';
import { WEAPONS, SAMPLE, CLASSES, DEFAULT_KEYS } from './data.js';
import { ProfileStore, decode, encode } from './store.js';
import { Scene } from './renderer.js';
import { Controls } from './input.js';
import { Audio } from './audio.js';
const $=id=>document.getElementById(id),esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let storage;try{storage=window.localStorage;}catch{storage={getItem(){throw Error('storage');},setItem(){throw Error('storage');},removeItem(){}};}
const store=new ProfileStore(storage);let profile=store.load(),g=new Arena(profile.session),home=true,modal=null,last=0,accumulator=0,renderTime=0,autosave=0,toastTimer=0,lastHud='',pendingImport=null;
const scene=new Scene($('v2-world')),audio=new Audio();audio.volume=profile.settings.sound;
const controls=new Controls(()=>home?null:g,{unlock:()=>audio.unlock(),pause:background=>pause(background),interact:()=>openRack()},profile.settings.keys);
function toast(message){$('v2-toast').textContent=message;$('v2-toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('v2-toast').classList.add('hidden'),3200);}
function sync(){profile.session=g.s;for(const t of g.s.targetsHit)if(!profile.tutorial.targets.includes(t))profile.tutorial.targets.push(t);profile.tutorial.dash ||=g.s.dashes>0;profile.tutorial.skill ||=g.s.usedSkill;const ok=store.write(profile);$('v2-save').textContent=ok?'已自动保存 · 继续本房':'暂未保存 · 设置可导出';if(!ok&&store.error)toast(store.error);return ok;}
function overview(){const l=profile.legacy;$('v2-legacy-note').textContent=store.error||(l.migrated?`旧旅程已备份并继承 · 旧币 ${l.coins} · 灰铁 ${l.iron}${l.memorial?' · 格伦修复纪念已保留':''}`:'首个第二版样板：先试四种武器，再挑战两波敌群。');$('v2-enter').innerHTML=g.s.mode==='trial'&&!g.s.done&&!g.s.dead?'继续本房 <span>→</span>':'进入训练庭 <span>→</span>';}
function show(title,html,type='menu'){controls.clear();g.pause();modal=type;$('v2-modal-title').textContent=title;$('v2-modal-body').innerHTML=html;$('v2-modal').classList.remove('hidden');$('v2-controls').classList.add('hidden');$('v2-close').focus();sync();}
function close(){modal=null;$('v2-modal').classList.add('hidden');if(!home){$('v2-controls').classList.remove('hidden');g.resume();}last=performance.now();accumulator=0;document.activeElement?.blur();}
function enter(){audio.unlock();document.activeElement?.blur();home=false;$('v2-home').classList.add('hidden');$('v2-hud').classList.remove('hidden');$('v2-controls').classList.remove('hidden');g.resume();last=performance.now();accumulator=0;if(g.s.done||g.s.dead)result();else if(!profile.legacy.migrated&&!profile.legacy.ending)show('第八次钟声','<p>七口钟，响了八次。军牌里传来一个声音。</p><p>序章里，你把艾琳的军牌交给了谁？这个选择会记录在第二版旅程中。</p><div class="button-row"><button data-action="honesty">向洛恩坦白</button><button data-action="silence">交给伊妲保管</button></div><div class="notice">当前先开放训练庭与试炼。完整续章和新职业将在后续版本开放。</div>','recap');else toast('左手移动，右手按住攻击；拖动攻击区可手动瞄准。');}
function practice(){g=new Arena(newSession('practice',g.p.weapons));profile.session=g.s;close();sync();toast('训练庭已恢复 · 补满生命、护盾和能量');}
function trial(){g=new Arena(newSession('trial',g.p.weapons));profile.session=g.s;close();sync();toast('两波试炼 · 敌人显形后行动，利用掩体和闪步');}
function pause(background=false){if(home){if(background)audio.suspend();return;}if(modal){if(!background)close();return;}show('片刻歇息',`<p>进度保留完整房内状态。回来后选择“继续本房”。</p><div class="menu-grid"><button data-action="resume" class="primary">继续本房</button><button data-action="rack">军械台</button><button data-action="settings">设置与存档</button><button data-action="notes">旧旅程与见闻</button><button data-action="help">操作说明</button><button data-action="home">保存并返回标题</button><button data-action="practice">返回训练庭并补给</button>${g.p.energy===0&&g.p.weapons.every(id=>WEAPONS[id].energy>0)?'<button data-action="emergency">将当前武器换为免费手枪</button>':''}</div>`);if(background)audio.suspend();}
function openRack(){if(home)return;if(g.s.mode==='trial'&&!g.s.done&&!g.s.dead){toast('试炼开始后固定两把武器，返回训练庭再调整。');return;}
 show('军械台 · 免费借用',`<p>可携带两把不同武器。装备只换枪，不增加能量；训练庭可免费补给。</p><div class="weapon-grid">${SAMPLE.map(id=>{const w=WEAPONS[id];return `<div class="weapon-card"><h3>${w.name} <small>标准</small></h3><p>${w.damage} × ${w.pellets} 伤害 · ${w.interval}s · 能耗 ${w.energy}<br>${w.behavior}</p>${[0,1].map(slot=>`<button data-equip="${id}" data-slot="${slot}" ${g.p.weapons[1-slot]===id?'disabled':''}>${g.p.weapons[slot]===id?'✓ ':''}槽 ${slot+1}${g.p.active===slot?' · 当前':''}</button>`).join('')}</div>`;}).join('')}</div><div class="button-row"><button data-action="refill">补给并重置移动靶</button><button data-action="potion" ${g.p.hp>=6||g.p.potions===0?'disabled':''}>安全房药剂 ${g.p.potions}/2 · 恢复2生命</button><button data-action="catalog">查看后续武器设计</button></div>`,'rack');}
function help(){show('巡界者的新步伐',`<p>左摇杆任意方向移动。右攻击区轻点只攻击一次；按住按武器间隔连发，拖动超过12像素手动瞄准，松手0.25秒后恢复辅助。没有目标时仍沿当前方向攻击。</p><div class="notice">护盾4秒未受伤后每秒恢复1点。闪步两次充能，每2.8秒补一次；灯环2秒清普通弹并减伤50%，冷却10秒。两把武器各自保留冷却。能量耗尽时，在暂停的军械台返回训练庭，免费借用手枪或短剑。</div><p>键盘：WASD 移动 · 鼠标瞄准/左键攻击 · Space 闪步 · Q 灯环 · E 切枪 · F 军械台 · Esc 暂停。按键可在设置重绑。</p><p>训练目标：射中三种移动靶、闪步一次、释放一次灯环。不限制时间，可随时进入试炼。样板中的试炼铜筹仅用于结算展示，不会兑换永久旧币。</p>`,'help');}
function settings(){show('设置与存档',`<label class="row">音量<input type="range" min="0" max="100" value="${profile.settings.sound*100}" data-setting="sound" aria-label="音量"></label><label class="row">轻微震屏<input type="checkbox" data-setting="shake" ${profile.settings.shake?'checked':''}></label><label class="row">画面帧率<select data-setting="fps"><option value="60" ${profile.settings.fps===60?'selected':''}>60 FPS</option><option value="30" ${profile.settings.fps===30?'selected':''}>30 FPS</option></select></label><p>键盘绑定：点击方框后按一个键；不接受重复按键。</p>${Object.entries(DEFAULT_KEYS).map(([key,value])=>`<label class="row">${{up:'上',down:'下',left:'左',right:'右',dash:'闪步',skill:'技能',swap:'切枪',interact:'交互'}[key]}<input class="key-input" readonly data-bind="${key}" value="${profile.settings.keys[key]===' '?'Space':esc(profile.settings.keys[key].toUpperCase())}" aria-label="${key}按键"></label>`).join('')}<div class="button-row"><button data-action="export">导出第二版旅程</button><button data-action="import">导入第二版备份</button><button data-action="reset-keys">恢复默认按键</button><button data-action="reset-confirm">新建第二版旅程</button></div><div class="notice">旧档在独立位置保留，升级前原文另有备份。序章继续使用原档；第二版导入不改序章。房内快照恢复，不重新发清房奖励。</div>`,'settings');}
function result(){show(g.s.dead?'灯锚将你带回':'试炼完成',`<p>${g.s.dead?'没有失去旧旅程中的财产与关键物品。可以回到训练庭重新尝试。':'两波敌群已清除。接下来可以换另一组武器，比较移动、射程与清弹的用途。'}</p><div class="notice">射击/挥击 ${g.s.shots} 次 · 命中 ${g.s.hits} 次<br>闪步 ${g.s.dashes} 次 · 承受伤害 ${g.s.damageTaken}<br>本次试炼铜筹 ${g.s.copper}（离开清零）</div><div class="button-row"><button data-action="practice" class="primary">返回训练庭</button><button data-action="trial">再试一次</button><button data-action="feedback">试玩记录表</button></div>`,'result');}
function confirmTrial(){show('实战试炼',`<p>当前装备：${g.p.weapons.map(id=>WEAPONS[id].name).join(' / ')}。面对雾噬鼠、裂爪犬和空壳弩手的两波攻击。每波结束恢复10能量。</p><div class="notice">带一把免费武器可在零能量时继续攻击。训练庭随时可返回；试炼不发永久奖励，不推进尚未开放的续章。</div><div class="button-row"><button data-action="trial" class="primary">带这两把武器进入试炼</button><button data-action="practice">返回训练庭并补给</button></div>`);}
function exportProfile(){try{const raw=encode(profile);if(window.AndroidBridge?.exportSave){window.AndroidBridge.exportSave(raw);return;}const url=URL.createObjectURL(new Blob([raw],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='暮边镇-七灯余响-旅程.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}catch{toast('导出失败，当前旅程仍在。');}}
function previewImport(raw){try{pendingImport=decode(raw);show('恢复第二版备份',`<p>旧结局：${pendingImport.legacy.ending==='honesty'?'向洛恩坦白':pendingImport.legacy.ending==='silence'?'交伊妲保管':'尚未选择'} · 试炼完成 ${pendingImport.trialWins} 次。</p><p>确认后替换第二版旅程；序章档案保留。</p><button data-action="confirm-import" class="primary">确认恢复</button>`,'import');}catch{toast('不是有效的第二版备份，当前旅程未改变。');}}
function notes(){const l=profile.legacy;show('旧旅程与见闻',`<p>军牌去向：${l.ending==='honesty'?'向洛恩坦白':l.ending==='silence'?'伊妲保管':'尚未记录'}。</p><p>旧币 ${l.coins} · 灰铁 ${l.iron} · 苦叶 ${l.leaf} · 苦叶膏 ${l.salve}<br>旧药剂 ${l.potions}，镇仓溢出药剂 ${l.warehousePotions}。${l.memorial?'旧剑强化已转为“格伦修复纪念”和6灰铁。':''}</p><div class="notice">本版迁移后安全返回训练庭，保留已结算资源、关键物与剧情记录。序章仍能在独立入口继续原旅程。</div><p>${l.logs.slice(-6).map(esc).join('<br>')||'旧旅程尚无对话记录。'}</p><p>训练：${profile.tutorial.targets.length}/3 种靶 · ${profile.tutorial.dash?'已闪步':'待闪步'} · ${profile.tutorial.skill?'已释放灯环':'待释放灯环'}<br>试炼完成 ${profile.trialWins} 次</p>`);}
function feedback(){show('真人试玩记录',`<p>这一版需要真人反馈，再扩展区域和武器。建议试玩10分钟，分别体验四种武器。</p><div class="notice">请记录：手机型号/系统、是否有漏输入、误锁目标、走位误触、受伤是否看得清；四类武器各有什么用途。帧率设置是绘制目标，不是实测性能承诺。</div><p>当前自动记录：攻击 ${g.s.shots} 次、命中 ${g.s.hits} 次、伤害 ${g.s.damageTaken}。这些数量不能证明输入延迟或真人手感。</p><button data-action="export">导出旅程供复现</button>`);}
const actions={resume:close,rack:openRack,settings,help,notes,trial,practice,refill:practice,feedback,export:exportProfile,import:()=>window.AndroidBridge?.importSave?window.AndroidBridge.importSave():$('v2-import').click(),potion:()=>{g.potion();sync();openRack();},honesty:()=>{profile.legacy.ending='honesty';close();sync();},silence:()=>{profile.legacy.ending='silence';close();sync();},home:()=>{sync();home=true;close();g.pause();$('v2-home').classList.remove('hidden');$('v2-hud').classList.add('hidden');$('v2-controls').classList.add('hidden');overview();},catalog:()=>show('武器设计目录',`<p>4把样板武器已实装，其余20把为后续设计数据，尚不可试射。四职业目前仅开放守灯人。</p><div class="catalog">${Object.values(WEAPONS).map(w=>`<div>${w.id} ${w.name} · ${w.rarity} · ${w.implemented?'已实装':'待制作'}<br><small>${w.behavior}</small></div>`).join('')}</div><p>${CLASSES.map(c=>c.name+'：'+(c.implemented?'已开放':'后续剧情解锁，待制作')).join('<br>')}</p>`), 'reset-keys':()=>{profile.settings.keys={...DEFAULT_KEYS};controls.keys=profile.settings.keys;settings();},'reset-confirm':()=>show('新建第二版旅程','<p>会替换当前第二版的试炼和教学记录。建议先导出；序章原始存档和升级前备份不会删除。</p><button data-action="reset" class="primary">确认新建第二版</button>'),'reset':()=>{try{profile=store.reset();g=new Arena(profile.session);controls.keys=profile.settings.keys;audio.volume=profile.settings.sound;actions.home();}catch{toast(store.error);}},'confirm-import':()=>{try{profile=store.import(encode(pendingImport));g=new Arena(profile.session);controls.keys=profile.settings.keys;audio.volume=profile.settings.sound;close();actions.home();toast('旅程已恢复，点击继续进入本房。');}catch{toast('恢复失败，原备份可再次导入。');}}};
$('v2-enter').onclick=enter;$('v2-home-settings').onclick=settings;$('v2-close').onclick=close;$('v2-pause').onclick=()=>pause();$('v2-rack').onclick=openRack;$('v2-mode').onclick=confirmTrial;
$('v2-modal-body').onclick=e=>{const b=e.target.closest('button');if(!b||b.disabled)return;audio.unlock();if(b.dataset.action==='emergency'){g.emergencyWeapon();sync();close();return;}if(b.dataset.equip){g.equip(b.dataset.equip,Number(b.dataset.slot));sync();openRack();return;}actions[b.dataset.action]?.();};
$('v2-modal-body').oninput=e=>{const k=e.target.dataset.setting;if(!k)return;profile.settings[k]=k==='shake'?e.target.checked:k==='sound'?Number(e.target.value)/100:Number(e.target.value);audio.volume=profile.settings.sound;sync();};
$('v2-modal-body').onkeydown=e=>{const binding=e.target.dataset.bind;if(!binding)return;e.preventDefault();e.stopPropagation();const key=e.key.toLowerCase();if(key.length!==1||Object.entries(profile.settings.keys).some(([b,v])=>b!==binding&&v===key)){toast('请选择未使用的单个字母或空格键');return;}profile.settings.keys[binding]=key;controls.keys=profile.settings.keys;e.target.value=key===' '?'Space':key.toUpperCase();sync();};
$('v2-import').onchange=async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>1048576){toast('文件超过1MB，未导入');return;}try{previewImport(await file.text());}catch{toast('无法读取文件');}};
$('v2-fullscreen').onclick=async()=>{try{await document.documentElement.requestFullscreen?.();await screen.orientation?.lock?.('landscape');}catch{toast('请手动横过手机');}};
function background(){controls.clear();if(!home&&!modal)pause(true);sync();audio.suspend();accumulator=0;last=performance.now();}
window.addEventListener('native-pause',background);window.addEventListener('pagehide',background);document.addEventListener('visibilitychange',()=>{if(document.hidden)background();else{last=performance.now();accumulator=0;}});window.addEventListener('native-resume',()=>{last=performance.now();accumulator=0;audio.unlock();});window.addEventListener('native-back',()=>home?settings():pause());window.addEventListener('native-import',e=>previewImport(e.detail));window.addEventListener('native-message',e=>toast(e.detail));window.addEventListener('resize',()=>{scene.resize();if(innerWidth<innerHeight)background();});
function hud(){const p=g.p,content=[p.hp,p.shield,Math.ceil(p.energy),p.dashCharges,Math.ceil(p.skillCooldown),p.active,...p.weapons,profile.tutorial.targets.length,profile.tutorial.dash,profile.tutorial.skill,g.s.mode].join('|');if(content===lastHud)return;lastHud=content;$('v2-life').textContent=`生命 ${p.hp}/6　护盾 ${p.shield}/6`;$('v2-energy').textContent=`能量 ${Math.floor(p.energy)} / 120`;$('v2-dash').innerHTML=`闪步 <small>${p.dashCharges} / 2</small>`;$('v2-skill').innerHTML=`灯环 <small>${p.skillCooldown>0?Math.ceil(p.skillCooldown)+'s':'就绪'}</small>`;$('v2-weapon').textContent=`${p.active+1} · ${g.weapon.name}　/　${WEAPONS[p.weapons[1-p.active]].name}`;$('v2-guide').textContent=g.s.mode==='trial'?'躲开 ! 预警 · 找掩体 · 按住攻击':`训练 ${Math.min(3,profile.tutorial.targets.length)}/3 种靶 · ${profile.tutorial.dash?'✓':'○'} 闪步 · ${profile.tutorial.skill?'✓':'○'} 灯环`;$('v2-rack').disabled=g.s.mode==='trial'&&!g.s.done&&!g.s.dead;}
function frame(now){const dt=last?Math.min(.05,(now-last)/1000):0;last=now;renderTime+=dt;if(!home&&!modal&&!document.hidden){accumulator+=dt;let steps=0;while(accumulator>=1/60&&steps++<3){g.update(1/60);accumulator-=1/60;}for(const e of g.drain()){if(e.type==='shot'){audio.play(e.weapon);if(profile.settings.shake)scene.shake=e.weapon==='S01'?1.5:.4;}else if(e.type==='hit')audio.play('hit',e.material);else if(['skill','dash','swap','hurt'].includes(e.type))audio.play(e.type);else if(e.type==='empty')toast('能量不足 · 切换免费手枪或短剑，或返回训练庭补给');else if(e.type==='win'){profile.trialWins++;sync();result();}else if(e.type==='dead'){sync();result();}else if(e.type==='save')sync();}for(const t of g.s.targetsHit)if(!profile.tutorial.targets.includes(t))profile.tutorial.targets.push(t);profile.tutorial.dash ||=g.s.dashes>0;profile.tutorial.skill ||=g.s.usedSkill;autosave+=dt;if(autosave>=5){sync();autosave=0;}}else accumulator=0;if(renderTime>=1/profile.settings.fps){if(!home)scene.draw(g);hud();renderTime=0;}requestAnimationFrame(frame);}
overview();scene.draw(g);requestAnimationFrame(frame);window.__duskboundBoot?.ready();
