import { WEAPONS, SAMPLE, ENEMIES, ROOM } from './data.js';
import { clamp, distance, angleDiff, visible, firstWall, segmentCircle, inSector, moveCircle, nextWaypoint } from './geometry.js';
export function newSession(mode='practice',weapons=['M01','P01']){
 return {mode,clock:0,wave:0,preview:mode==='trial'?.8:0,done:false,dead:false,rewarded:[],copper:0,nextId:20,shots:0,hits:0,damageTaken:0,dashes:0,cleared:0,
  player:{...ROOM.spawn,hp:6,shield:6,energy:120,potions:1,angle:0,active:1,weapons:[...weapons],cooldowns:[0,0],switchTime:0,dashCharges:2,dashRecharge:0,dashTime:0,dashX:0,dashY:0,invulnerable:0,lastHurt:-10,shieldTick:0,skillCooldown:0,ring:0,breakBoost:0,melee:null},enemies:[],bullets:[],pendingShots:[],targetId:null,targetDelay:0,targetsHit:[],usedSkill:false};
}
export class Arena {
 constructor(session=newSession()){this.s=session;this.input={x:0,y:0};this.events=[];this.effects=[];this.paused=false;this.manualTime=0;this.manualAngle=0;this.manualHeld=false;this.attackHeld=false;this.repeatAt=0;this.bufferDash=0;if(!session.enemies.length&&session.mode==='practice')this.addTargets();}
 get p(){return this.s.player;} get weapon(){return WEAPONS[this.p.weapons[this.p.active]];}
 event(type,data={}){this.events.push({type,...data});}
 drain(){const events=this.events;this.events=[];return events;}
 pause(){this.paused=true;this.clearInput();}
 resume(){this.clearInput();this.paused=false;}
 clearInput(){this.input={x:0,y:0};this.attackHeld=false;this.repeatAt=0;this.manualHeld=false;this.bufferDash=0;}
 addTargets(){this.s.enemies=[['static',300,98],['strafe',472,109],['orbit',518,249],['cover',300,243]].map(([motion,x,y],i)=>({id:i+1,kind:'target',motion,x:x+(motion==='orbit'?26:0),y,ox:x,oy:y,hp:40,maxHp:40,r:8,state:'idle',timer:0,angle:0,tx:x,ty:y,flash:0,stun:0,vx:0,vy:0,hit:[]}));}
 aim(angle,held=false){this.manualAngle=angle;this.manualTime=.25;this.manualHeld=held;this.p.angle=angle;this.s.targetId=null;}
 updateAim(dt){const s=this.s,p=this.p;s.targetDelay=Math.max(0,s.targetDelay-dt);if(this.manualHeld||this.manualTime>0){this.manualTime=Math.max(0,this.manualTime-dt);p.angle=this.manualAngle;s.targetId=null;return;}
  const candidates=s.enemies.filter(e=>e.hp>0&&e.state!=='spawn'&&distance(p,e)<=this.weapon.range+e.r&&visible(p,e,ROOM.walls,this.weapon.id==='M01'?0:this.weapon.id==='S01'?2:3));
  let target=candidates.find(e=>e.id===s.targetId);if(!target){s.targetId=null;if(s.targetDelay>0)return;candidates.sort((a,b)=>this.score(a)-this.score(b));target=candidates[0];if(target){s.targetId=target.id;s.targetDelay=.12;}}
  if(target){const lead=this.weapon.id==='P01'?Math.min(.12,distance(p,target)/this.weapon.speed):0;p.angle=Math.atan2(target.y+(target.vy||0)*lead-p.y,target.x+(target.vx||0)*lead-p.x);}
 }
 score(e){return distance(this.p,e)+Math.abs(angleDiff(Math.atan2(e.y-this.p.y,e.x-this.p.x),this.p.angle))*25-(distance(this.p,e)<35?25:0);}
 pressAttack(){if(this.paused||this.s.dead||this.s.done)return false;this.attackHeld=true;this.updateAim(0);const fired=this.fire();this.repeatAt=this.weapon.interval;return fired;}
 releaseAttack(){this.attackHeld=false;}
 fire(){const p=this.p,w=this.weapon;if(this.paused||this.s.dead||this.s.done||p.switchTime>0||p.cooldowns[p.active]>1e-8||p.dashTime>0)return false;
  if(p.energy<w.energy){this.event('empty');return false;}p.energy-=w.energy;p.cooldowns[p.active]=w.interval;this.s.shots++;const origin={x:p.x,y:p.y};
  if(w.id==='M01')p.melee={angle:p.angle,time:0,hit:[],cleared:[]};else{const group=this.s.nextId++;for(let i=0;i<w.pellets;i++){const angle=p.angle+(w.pellets===1?0:((i/(w.pellets-1))-.5)*26*Math.PI/180);this.s.bullets.push({id:this.s.nextId++,group,team:'friend',kind:w.id==='W01'?'needle':'round',x:origin.x,y:origin.y,vx:Math.cos(angle)*w.speed,vy:Math.sin(angle)*w.speed,damage:w.damage,r:w.id==='S01'?2:3,remaining:w.range,pierce:0,hit:[],source:w.id});}}
  this.effects.push({kind:'muzzle',x:p.x,y:p.y,angle:p.angle,life:.08,weapon:w.id});this.event('shot',{weapon:w.id});return true;
 }
 swap(){if(this.paused||this.s.dead)return false;this.attackHeld=false;this.repeatAt=0;this.p.active=1-this.p.active;this.p.switchTime=.12;this.p.melee=null;this.s.targetId=null;this.event('swap');return true;}
 emergencyWeapon(){if(this.p.energy>0||this.p.weapons.some(id=>WEAPONS[id].energy===0))return false;this.attackHeld=false;this.p.weapons[this.p.active]='P01';this.p.switchTime=.12;this.p.melee=null;return true;}
 equip(id,slot){if(!SAMPLE.includes(id)||![0,1].includes(slot)||this.s.mode==='trial'&&!this.s.done)return false;if(this.p.weapons[1-slot]===id)return false;this.clearInput();this.p.weapons[slot]=id;this.p.cooldowns[slot]=0;this.p.melee=null;this.s.targetId=null;return true;}
 dash(){const p=this.p;if(this.paused||this.s.dead||this.s.done)return false;if(p.switchTime>0||p.melee&&p.melee.time<.04){this.bufferDash=.1;return false;}if(p.dashCharges<=0||p.dashTime>0)return false;const d=Math.hypot(this.input.x,this.input.y),a=d>0?Math.atan2(this.input.y,this.input.x):p.angle;p.dashX=Math.cos(a);p.dashY=Math.sin(a);p.dashTime=.18;p.invulnerable=Math.max(p.invulnerable,.12);p.dashCharges--;if(!p.dashRecharge)p.dashRecharge=2.8;p.melee=null;this.s.dashes++;this.event('dash');return true;}
 skill(){const p=this.p;if(this.paused||this.s.dead||this.s.done||p.skillCooldown>0)return false;p.skillCooldown=10;p.ring=2;this.s.usedSkill=true;this.event('skill');return true;}
 potion(){if(this.s.mode==='trial'&&!this.s.done)return false;if(this.p.hp>=6||this.p.potions===0)return false;this.p.potions--;this.p.hp=Math.min(6,this.p.hp+2);return true;}
 hurt(damage,group){const p=this.p;if(this.s.dead||p.invulnerable>0||this.s.mode==='practice')return false;const before=p.shield;const amount=p.ring>0?damage*.5:damage;p.shield=Math.max(0,p.shield-amount);p.hp=Math.max(0,p.hp-Math.max(0,amount-before));p.invulnerable=.55;p.lastHurt=this.s.clock;p.shieldTick=0;if(before>0&&p.shield===0){p.breakBoost=1;p.invulnerable=Math.max(.35,p.invulnerable);}this.s.damageTaken+=amount;this.event('hurt',{group});if(p.hp===0){this.s.dead=true;this.clearInput();this.s.bullets=[];this.event('dead');}return true;}
 hitEnemy(e,damage,angle,knock=3){if(e.hp<=0)return;e.hp=Math.max(0,e.hp-damage);e.flash=.035;e.stun=.025;this.s.hits++;if(e.kind==='target'&&!this.s.targetsHit.includes(e.motion))this.s.targetsHit.push(e.motion);if(e.kind!=='target')moveCircle(e,Math.cos(angle)*knock,Math.sin(angle)*knock,ROOM.walls,ROOM.bounds,e.r);
  this.effects.push({kind:'hit',x:e.x,y:e.y,angle,life:.12});const number=this.effects.find(f=>f.kind==='number'&&f.id===e.id&&f.life>.57);if(number)number.value+=damage;else{const old=this.effects.filter(f=>f.kind==='number'&&f.id===e.id);if(old.length>=2)old[0].life=0;this.effects.push({kind:'number',id:e.id,x:e.x,y:e.y-26,value:damage,life:.65});}this.event('hit',{material:e.kind==='archer'?'metal':e.kind==='target'?'wood':'mist'});if(e.hp===0){this.effects.push({kind:'death',x:e.x,y:e.y,life:.35});this.event('kill');}}
 spawnWave(){const kinds=this.s.wave===0?['rat','rat','archer','dog']:['dog','archer','rat'];const spots=[{x:535,y:100},{x:510,y:265},{x:310,y:90},{x:310,y:283},{x:80,y:82},{x:80,y:288}];const used=[];this.s.enemies=kinds.map((kind,i)=>{const spot=spots.filter(pos=>distance(pos,this.p)>=80&&!used.includes(pos)).sort((a,b)=>distance(b,this.p)-distance(a,this.p))[0];if(!spot)throw Error('没有安全的生成位置');used.push(spot);const d=ENEMIES[kind];return{id:this.s.nextId++,kind,x:spot.x,y:spot.y,ox:spot.x,oy:spot.y,hp:d.hp,maxHp:d.hp,r:d.r,state:'spawn',timer:.8,angle:0,tx:spot.x,ty:spot.y,flash:0,stun:0,vx:0,vy:0,hit:[]};});this.s.preview=0;this.event('wave');}
 updateEnemy(e,dt){const s=this.s,p=this.p;if(e.hp<=0){if(e.kind==='target'){e.timer+=dt;if(e.timer>1.5){e.hp=e.maxHp;e.timer=0;}}return;}
  e.flash=Math.max(0,e.flash-dt);if(e.stun>0){e.stun-=dt;return;}
  if(e.kind==='target'){const old={x:e.x,y:e.y};const t=s.clock;e.x=e.ox+(e.motion==='strafe'?Math.sin(t*1.6)*40:e.motion==='orbit'?Math.cos(t)*26:e.motion==='cover'?Math.sin(t*.7)*52:0);e.y=e.oy+(e.motion==='orbit'?Math.sin(t)*24:0);e.vx=(e.x-old.x)/dt;e.vy=(e.y-old.y)/dt;return;}
  const d=ENEMIES[e.kind];e.timer-=dt;if(e.state==='spawn'){if(e.timer<=0)e.state='chase';return;}if(e.state==='recover'){if(e.timer<=0)e.state='chase';return;}
  if(e.state==='charge'){moveCircle(e,Math.cos(e.angle)*190*dt,Math.sin(e.angle)*190*dt,ROOM.walls,ROOM.bounds,e.r);if(distance(p,e)<=e.r+5)this.hurt(2,e.id);if(e.timer<=0){e.state='recover';e.timer=.9;}return;}
  if(e.state==='windup'){if(e.timer>0)return;if(e.kind==='archer'){const group=s.nextId++;for(let i=-1;i<=1;i++){const a=e.angle+i*.23;s.bullets.push({id:s.nextId++,group,team:'enemy',kind:'round',x:e.x,y:e.y,vx:Math.cos(a)*78,vy:Math.sin(a)*78,damage:1,r:2.5,remaining:420,pierce:0,hit:[],source:'archer'});}e.state='recover';e.timer=1.25;}else if(e.kind==='dog'){e.state='charge';e.timer=.48;}else{if(distance(p,e)<23&&visible(e,p,ROOM.walls))this.hurt(1,e.id);e.state='recover';e.timer=.8;}return;}
  const dist=distance(e,p);e.angle=Math.atan2(p.y-e.y,p.x-e.x);if(dist<=d.range&&visible(e,p,ROOM.walls,e.kind==='archer'?2.5:e.r)){e.state='windup';e.timer=d.tell;e.tx=p.x;e.ty=p.y;return;}const speed=d.speed;const old={x:e.x,y:e.y},waypoint=nextWaypoint(e,p,ROOM.walls,e.r);const heading=Math.atan2(waypoint.y-e.y,waypoint.x-e.x);moveCircle(e,Math.cos(heading)*speed*dt,Math.sin(heading)*speed*dt,ROOM.walls,ROOM.bounds,e.r);
  e.vx=(e.x-old.x)/dt;e.vy=(e.y-old.y)/dt;
 }
 updateBullets(dt){const p=this.p,s=this.s;const packets=new Map();for(const b of s.bullets){if(b.remaining<=0)continue;const a={x:b.x,y:b.y};const length=Math.min(b.remaining,Math.hypot(b.vx,b.vy)*dt),angle=Math.atan2(b.vy,b.vx),z={x:a.x+Math.cos(angle)*length,y:a.y+Math.sin(angle)*length};const wall=firstWall(a,z,ROOM.walls,b.r);let stop=wall===null?1:wall;
   if(b.team==='friend'){const hits=s.enemies.filter(e=>e.hp>0&&e.state!=='spawn'&&!b.hit.includes(e.id)).map(e=>({e,t:segmentCircle(a,z,e,e.r+b.r)})).filter(o=>o.t!==null&&o.t<stop).sort((x,y)=>x.t-y.t);for(const h of hits){this.hitEnemy(h.e,b.damage,angle,b.source==='S01'?5:3);b.hit.push(h.e.id);if(b.pierce--<=0){stop=h.t;b.remaining=0;break;}}}
   else{const clear=p.ring>0?segmentCircle(a,z,p,24+b.r):null;const t=segmentCircle(a,z,p,5+b.r);if(clear!==null&&clear<=stop){stop=clear;b.remaining=0;this.effects.push({kind:'spark',x:a.x+(z.x-a.x)*clear,y:a.y+(z.y-a.y)*clear,life:.12});}else if(t!==null&&t<stop){const prev=packets.get(b.group)||0;packets.set(b.group,Math.max(prev,b.damage));stop=t;b.remaining=0;}}
   b.x=a.x+(z.x-a.x)*stop;b.y=a.y+(z.y-a.y)*stop;b.remaining-=length;if(wall!==null&&stop>=wall)b.remaining=0;const bounds=ROOM.bounds;if(b.x<bounds.x||b.x>bounds.x+bounds.w||b.y<bounds.y||b.y>bounds.y+bounds.h)b.remaining=0;
  }for(const [group,damage]of packets)this.hurt(damage,group);s.bullets=s.bullets.filter(b=>b.remaining>0);}
 update(dt){if(this.paused||this.s.dead||this.s.done)return;dt=clamp(dt,0,1/30);const s=this.s,p=this.p;s.clock+=dt;this.updateAim(dt);for(const k of ['switchTime','invulnerable','skillCooldown','ring','breakBoost'])p[k]=Math.max(0,p[k]-dt);p.cooldowns=p.cooldowns.map(t=>Math.max(0,t-dt));
  if(p.dashCharges<2){p.dashRecharge-=dt;if(p.dashRecharge<=1e-8){p.dashCharges++;p.dashRecharge=p.dashCharges<2?2.8+p.dashRecharge:0;}}
  if(s.clock-p.lastHurt>=4&&p.shield<6){p.shieldTick+=dt;if(p.shieldTick>=1){p.shield=Math.min(6,p.shield+1);p.shieldTick-=1;}}
  if(this.bufferDash>0){this.bufferDash-=dt;if(p.switchTime<=0&&(!p.melee||p.melee.time>=.04)){this.bufferDash=0;this.dash();}}
  const norm=Math.max(1,Math.hypot(this.input.x,this.input.y));if(p.dashTime>0){const step=Math.min(dt,p.dashTime);moveCircle(p,p.dashX*30/.18*step,p.dashY*30/.18*step,ROOM.walls,ROOM.bounds);p.dashTime=Math.max(0,p.dashTime-dt);}else{const firing=p.cooldowns[p.active]>0;const speed=112*(p.breakBoost>0?1.15:1)*(firing?(this.weapon.id==='M01'?.9:this.weapon.id==='S01'?.95:1):1);moveCircle(p,this.input.x/norm*speed*dt,this.input.y/norm*speed*dt,ROOM.walls,ROOM.bounds);}
  // Entity separation has no effect while dashing; walls are always authoritative.
  if(p.dashTime<=0)for(const e of s.enemies){if(e.hp<=0||e.kind==='target'||e.state==='spawn')continue;const d=distance(p,e),r=7+e.r;if(d<r){const a=d>.001?Math.atan2(p.y-e.y,p.x-e.x):0;moveCircle(p,Math.cos(a)*(r-d)*.5,Math.sin(a)*(r-d)*.5,ROOM.walls,ROOM.bounds);moveCircle(e,-Math.cos(a)*(r-d)*.5,-Math.sin(a)*(r-d)*.5,ROOM.walls,ROOM.bounds,e.r);}}
  if(this.attackHeld){this.repeatAt-=dt;if(this.repeatAt<=1e-8){this.fire();this.repeatAt=this.weapon.interval;}}
  if(p.melee){const m=p.melee;m.time+=dt;if(m.time>=.04&&m.time<=.11){for(const e of s.enemies)if(e.hp>0&&e.state!=='spawn'&&!m.hit.includes(e.id)&&inSector(p,e,m.angle,22,100*Math.PI/180,e.r)&&visible(p,e,ROOM.walls)){m.hit.push(e.id);this.hitEnemy(e,15,m.angle,3);}for(const b of s.bullets)if(b.team==='enemy'&&b.kind==='round'&&inSector(p,b,m.angle,22,100*Math.PI/180,b.r)&&visible(p,b,ROOM.walls))b.remaining=0;}if(m.time>=.24)p.melee=null;}
  for(const e of s.enemies)this.updateEnemy(e,dt);this.updateBullets(dt);this.effects=this.effects.filter(e=>(e.life-=dt)>0);
  if(s.mode==='trial'&&!s.dead){if(s.preview>0){s.preview-=dt;if(s.preview<=0)this.spawnWave();}else if(!s.enemies.some(e=>e.hp>0)){if(!s.rewarded.includes(s.wave)){s.rewarded.push(s.wave);s.copper+=10;p.energy=Math.min(120,p.energy+10);s.cleared++;this.event('save');}if(s.wave===0){s.wave=1;s.preview=1.5;s.bullets=[];this.event('nextWave');}else{s.done=true;this.clearInput();s.bullets=[];this.event('win');}}}
 }
}
