import { DEFAULT_KEYS } from './data.js';
export class Controls {
 constructor(getArena,callbacks,keys=DEFAULT_KEYS){this.getArena=getArena;this.callbacks=callbacks;this.keys=keys;this.pressed=new Set();this.stickId=null;this.fireId=null;this.bind();}
 clear(){this.pressed.clear();this.stickId=null;this.fireId=null;this.getArena()?.clearInput();document.getElementById('v2-knob').style.transform='';}
 bind(){const stick=document.getElementById('v2-stick'),fire=document.getElementById('v2-fire'),knob=document.getElementById('v2-knob');
  const motion=e=>{if(e.pointerId!==this.stickId)return;const r=stick.getBoundingClientRect(),dx=e.clientX-r.x-r.width/2,dy=e.clientY-r.y-r.height/2,d=Math.max(r.width*.32,Math.hypot(dx,dy));const g=this.getArena();if(g)g.input={x:dx/d,y:dy/d};knob.style.transform=`translate(${dx/d*28}px,${dy/d*28}px)`;};
  stick.addEventListener('pointerdown',e=>{e.preventDefault();if(this.stickId!==null)return;this.callbacks.unlock();this.stickId=e.pointerId;stick.setPointerCapture(e.pointerId);motion(e);});stick.addEventListener('pointermove',motion);const stop=e=>{if(e.pointerId!==this.stickId)return;this.stickId=null;knob.style.transform='';if(this.getArena())this.getArena().input={x:0,y:0};};for(const name of ['pointerup','pointercancel','lostpointercapture'])stick.addEventListener(name,stop);
  fire.addEventListener('pointerdown',e=>{e.preventDefault();if(this.fireId!==null)return;this.callbacks.unlock();this.fireId=e.pointerId;this.fireStart={x:e.clientX,y:e.clientY};fire.setPointerCapture(e.pointerId);this.getArena()?.pressAttack();});
  fire.addEventListener('pointermove',e=>{if(e.pointerId!==this.fireId)return;const x=e.clientX-this.fireStart.x,y=e.clientY-this.fireStart.y;if(Math.hypot(x,y)>12)this.getArena()?.aim(Math.atan2(y,x),true);});
  const end=e=>{if(e.pointerId!==this.fireId)return;this.fireId=null;const g=this.getArena();if(g){g.releaseAttack();if(g.manualHeld)g.manualTime=.25;g.manualHeld=false;}};for(const name of ['pointerup','pointercancel','lostpointercapture'])fire.addEventListener(name,end);
  for(const [id,fn]of [['v2-dash','dash'],['v2-skill','skill'],['v2-swap','swap']])document.getElementById(id).addEventListener('pointerdown',e=>{e.preventDefault();this.callbacks.unlock();this.getArena()?.[fn]();});
  const canvas=document.getElementById('v2-world');canvas.addEventListener('pointermove',e=>{if(e.pointerType!=='mouse')return;const g=this.getArena();if(!g)return;const r=canvas.getBoundingClientRect(),x=(e.clientX-r.x)/r.width*640,y=(e.clientY-r.y)/r.height*360;g.aim(Math.atan2(y-g.p.y,x-g.p.x),true);});canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button===0){this.callbacks.unlock();canvas.setPointerCapture(e.pointerId);this.getArena()?.pressAttack();}});for(const n of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(n,()=>this.getArena()?.releaseAttack());
  window.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)&&e.key!=='Escape')return;if(e.key==='Escape'){this.callbacks.pause();return;}const key=e.key.toLowerCase();if(!Object.values(this.keys).includes(key))return;e.preventDefault();if(e.repeat)return;this.pressed.add(key);this.callbacks.unlock();const g=this.getArena();if(key===this.keys.dash)g?.dash();if(key===this.keys.skill)g?.skill();if(key===this.keys.swap)g?.swap();if(key===this.keys.interact)this.callbacks.interact();this.keyboardMove();});window.addEventListener('keyup',e=>{this.pressed.delete(e.key.toLowerCase());this.keyboardMove();});window.addEventListener('blur',()=>{this.clear();this.callbacks.pause(true);});window.addEventListener('contextmenu',e=>e.preventDefault());
 }
 keyboardMove(){if(this.stickId!==null)return;const g=this.getArena();if(g)g.input={x:Number(this.pressed.has(this.keys.right))-Number(this.pressed.has(this.keys.left)),y:Number(this.pressed.has(this.keys.down))-Number(this.pressed.has(this.keys.up))};}
}
