export class Input {
  constructor(getGame,onPause,onInteract,sound){this.getGame=getGame;this.onPause=onPause;this.onInteract=onInteract;this.sound=sound;this.keys=new Set();this.attackHeld=false;this.attackTimer=0;this.stickPointer=null;this.stick={x:0,y:0};this.bind();}
  bind(){const stick=document.getElementById('joystick'),knob=document.getElementById('stick-knob');
    const move=e=>{if(e.pointerId!==this.stickPointer)return;const r=stick.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),radius=r.width*.34,d=Math.hypot(dx,dy),f=d>radius?radius/d:1;this.stick={x:dx*f/radius,y:dy*f/radius};knob.style.transform=`translate(${dx*f}px,${dy*f}px)`;};
    stick.addEventListener('pointerdown',e=>{e.preventDefault();this.sound.unlock();if(this.stickPointer!==null)return;this.stickPointer=e.pointerId;stick.setPointerCapture(e.pointerId);move(e);});stick.addEventListener('pointermove',move);
    const release=e=>{if(e.pointerId===this.stickPointer){this.stickPointer=null;this.stick={x:0,y:0};knob.style.transform='';}};stick.addEventListener('pointerup',release);stick.addEventListener('pointercancel',release);stick.addEventListener('lostpointercapture',release);
    for(const [id,action]of [['attack','attack'],['dodge','dodge'],['block','block'],['potion','potion']]){const el=document.getElementById(id);el.addEventListener('pointerdown',e=>{e.preventDefault();this.sound.unlock();el.setPointerCapture(e.pointerId);el.classList.add('pressed');const g=this.getGame();if(!g)return;if(action==='block')g.block(true);else g[action]();if(action==='attack')this.attackHeld=true;});const up=()=>{el.classList.remove('pressed');if(action==='block')this.getGame()?.block(false);if(action==='attack')this.attackHeld=false;};el.addEventListener('pointerup',up);el.addEventListener('pointercancel',up);el.addEventListener('lostpointercapture',up);}
    window.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;const key=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' ','escape'].includes(key))e.preventDefault();if(e.repeat)return;this.keys.add(key);this.sound.unlock();const g=this.getGame();if(key==='escape'){this.onPause();return;}if(!g)return;if(key==='j'||key===' '){g.attack();this.attackHeld=true;}if(key==='k')g.dodge();if(key==='l')g.block(true);if(key==='h')g.potion();if(key==='e'||key==='enter')this.onInteract();});
    window.addEventListener('keyup',e=>{const key=e.key.toLowerCase();this.keys.delete(key);if(key==='l')this.getGame()?.block(false);if(key==='j'||key===' ')this.attackHeld=false;});window.addEventListener('blur',()=>this.clear());window.addEventListener('contextmenu',e=>e.preventDefault());
  }
  clear(){this.keys.clear();this.stick={x:0,y:0};this.stickPointer=null;this.attackHeld=false;this.getGame()?.block(false);document.getElementById('stick-knob').style.transform='';document.querySelectorAll('.pressed').forEach(e=>e.classList.remove('pressed'));}
  update(dt){const g=this.getGame();if(!g)return;const has=k=>this.keys.has(k)?1:0;g.input.x=this.stick.x+has('d')+has('arrowright')-has('a')-has('arrowleft');g.input.y=this.stick.y+has('s')+has('arrowdown')-has('w')-has('arrowup');this.attackTimer-=dt;if(this.attackHeld&&this.attackTimer<=0){this.attackTimer=.12;g.attack();}}
}
